Hotkey NumLock, NumLockFunction
Hotkey NumpadDiv, DivFunction
Hotkey NumpadMult, MultFunction
Hotkey $Backspace, BSFunction
Hotkey Numpad7, SevenFunction
Hotkey NumpadHome, SevenFunction
Hotkey Numpad8, EightFunction
Hotkey +Numpad8, EightFunction
Hotkey Numpad9, NineFunction
Hotkey NumpadSub, SubFunction
Hotkey Numpad4, FourFunction
Hotkey NumpadLeft, FourFunction
Hotkey Numpad5, FiveFunction
Hotkey +Numpad5, FiveFunction
Hotkey Numpad6, SixFunction
Hotkey NumpadAdd, AddFunction
Hotkey Numpad1, OneFunction
Hotkey Numpad2, TwoFunction
Hotkey Numpad3, ThreeFunction
Hotkey NumpadEnter, EnterFunction
Hotkey +NumpadEnter, EnterFunction
Hotkey Numpad0, ZeroFunction
;Hotkey Numpad000, TripleZeroFunction
Hotkey NumpadDot, DotFunction
